load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "8272287b125a23bfc79650ecbbc045ebcaee4d632338b1a50aad34357bcbadce",
    strip_prefix = "rules_python-0.23.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.23.0/rules_python-0.23.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()


python_register_toolchains(
     #name = "python310",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    # python_version = "3.10",
     name = "python3_9",
     python_version = "3.9",
)

#load("@python310_resolved_interpreter//:defs.bzl", "interpreter")

load("@python3_9//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_parse")


# Create a central repo that knows about the dependencies needed from
# requirements_lock.txt.
pip_parse(
   name = "my_deps",
   python_interpreter_target = interpreter,
   requirements_lock = "//:requirements.txt",
)
# Load the starlark macro which will define your dependencies.
load("@my_deps//:requirements.bzl", "install_deps")
# Call it to define repos for your requirements.
install_deps()


# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# http_archive(
#     name = "rules_python",
#     sha256 = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4",
#     strip_prefix = "rules_python-0.13.0",
#     url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz",
# )
 
# load("@rules_python//python:pip.bzl", "pip_install")
 
# pip_install(
#    name = "python_deps",
#    requirements = "//:requirements.txt",
# )

